POST http://localhost:4000/addProduct
Content-Type: application/json

   {
    "name" : "iphone 13",
     "image" : "http://www.thunderclient.com/images/thunder-screenshot-v8.png?v=3",
     "price" : 35000
   } 

###
POST http://localhost:4000/removeProduct
Content-Type: application/json

{
   "id":"669402fd71c2adac315831ee"
}

###
GET http://localhost:4000/allProducts